n=2; %number of state
q=0.1; %std of process
r=0.1; %std of measurement
Q=q^2*eye(n); % covariance of process
R=r^2; % covariance of measurement
%f=@(x)[x(2);x(3);0.05x(1)(x(2)+x(3))]; % nonlinear state equations
%h=@(x)x(1); % measurement equation
s=[0;0]; % initial state
x=s;%+qrandn(3,1); %initial state % initial state with noise
P = eye(n); % initial state covraiance
N=20; % total dynamic steps
xV = zeros(n,N); %estmate % allocate memory
sV = zeros(n,N); %actual
zV = zeros(1,N);
for k=1:N
z = s(2);%h(s) ;%+ rrandn; % measurments
sV(:,k)= s; % save actual state
zV(k) = z; % save measurment
[x, P] = ukf(x,P,z,Q,R); % ekf
xV(:,k) = x; % save estimate
s = f(s) ;%+ q*randn(3,1); % update process
end
